name: Hello Github Action

on:
   push:
      branches:[develop]

jobs:
   say_Hello:
      runs-on: ubuntu-latest
      steps:
         -name: print greeting 
         run: echo "Hello , from Github Action!"